<?php

return array(
    array(
        'name'=>'top_menu',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'sidebar',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'language',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'searchANewDilers',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'about_page',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'trade_page',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'patent_page',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'randProduction',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'ourAdvantages',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'logo',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'mainPageProduction',
        'maxItemCount'=>5
    ),
    array(
        'name'=>'mainPageArticle',
        'maxItemCount'=>5
    ),
);