<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Error' => 'Помилка',
    'tel' => 'тел.',
    'fax' => 'факс',
    'email' => 'email',

    'COMPANY' => 'КОМПАНІЯ',
    'CONTACTS' => 'КОНТАКТИ',
    'Download Price' => 'ЗАВАНТАЖИТИ  ПРАЙС',
    'Error' => 'Помилка',
    'Expert Advice' => 'ПОРАДИ ЕКСПЕРТІВ',
    'Georgia' => 'Грузія',
    'History' => 'ІСТОРІЯ',
    'Mailing address:' => 'Поштова адреса:',
    'NEWS' => 'НОВИНИ',
    'Officials TM "Ahrokorm" outside Ukraine' => 'Офіційні представники ТМ «Агрокорм» за межами України',
    'PRODUCTION' => 'ПРОДУКЦІЯ',
    'Proposals for the domestic market' => 'Пропозиції для внутрішнього ринку',
    'Registered address:' => 'Юридична адреса:',
    'SERVICES' => 'ПОСЛУГИ',
    'TIPS export' => 'ПОРАДИ ЕКСПЕРТІВ',
    'leadership' => 'КЕРІВНИЦТВО',
    'production' => 'Виробництво',
    'For this section no active products.' => 'Для даного розділу немає активної продукції.',
    'From the' => 'від',
    'GROUND' => 'ЗЕМЛІ',
    'INTERNAL MARKET' => 'ВНУТРІШНІЙ РИНОК',
    'to' => 'до',
    'LORD' => 'ГОСПОДАРЯ',
    'EXPORT' => 'ЕКСПОРТ',
);
