<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Error' => 'Ошибка',
    'tel' => 'тел.',
    'fax' => 'факс',
    'email' => 'email',
    'we write' => 'напишите нам',
    'Name' => 'Ф.И.О',
    'Email' => 'Email',
    'Message' => 'Сообщение',
    'Send' => 'Отправить',
    'Phone' => 'Телефон',

    'COMPANY' => 'КОМПАНИЯ',
    'CONTACTS' => 'КОНТАКТЫ',
    'Download Price' => 'ЗАГРУЗИТЬ ПРАЙС',
    'Error' => 'Ошибка',
    'Expert Advice' => 'СОВЕТЫ ЭКСПЕРТОВ',
    'Georgia' => 'Грузия',
    'History' => 'ИСТОРИЯ',
    'Mailing address:' => 'Почтовый адрес:',
    'NEWS' => 'НОВОСТИ',
    'Officials TM "Ahrokorm" outside Ukraine' => 'Официальные представители ТМ «Агрокорм» за пределами Украины',
    'PRODUCTION' => 'ПРОДУКЦИЯ',
    'Proposals for the domestic market' => 'Предложения для внутреннего рынка',
    'Registered address:' => 'Юридический адрес:',
    'SERVICES' => 'УСЛУГИ',
    'TIPS export' => 'СОВЕТЫ ЭКСПЕРТОВ',
    'leadership' => 'РУКОВОДСТВО',
    'production' => 'Производство',
    'For this section no active products.' => 'Для данного раздела нет активной продукции.',
    'From the' => 'от',
    'GROUND' => 'ЗЕМЛИ',
    'INTERNAL MARKET' => 'ВНУТРЕННИЙ РЫНОК',
    'to' => 'до',
    'LORD' => 'ХОЗЯИНА',
    'EXPORT' => 'ЭКСПОРТ',
);
